[package]
name = "chess"
version = "0.3.0"
authors = ["Alice Micheloni <alicemicheloni@tutanota.com>"]
edition = "2018"

[dependencies]
shakmaty = "0.15.0"

[dependencies.sdl2]
version = "0.32.0"
default-features = false
features = ["image"]

[features]
default = []
portable = []
